let x = [
  {
    username: "a",
    socketId: "yyLdQTaWb0xPj4v9AAAH",
    room: "a",
    letters: [
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-0": "" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-1": "" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-2": "a" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-3": "t" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-4": "f" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-5": "t" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-6": "s" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-7": "m" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-8": "i" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-9": "f" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-10": "o" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-11": "v" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-12": "y" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-13": "c" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-14": "i" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-15": "t" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-16": "a" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-17": "m" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-18": "o" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-19": "d" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-20": "o" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-21": "o" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-22": "e" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-23": "k" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-24": "f" },
      { "player-yyLdQTaWb0xPj4v9AAAH-letter-25": "e" },
    ],
    words: [
      { "player-yyLdQTaWb0xPj4v9AAAH-word-1": "gv" },
      { "player-yyLdQTaWb0xPj4v9AAAH-word-2": "" },
      { "player-yyLdQTaWb0xPj4v9AAAH-word-3": "" },
      { "player-yyLdQTaWb0xPj4v9AAAH-word-4": "" },
      { "player-yyLdQTaWb0xPj4v9AAAH-word-5": "" },
      { "player-yyLdQTaWb0xPj4v9AAAH-word-6": "" },
    ],
    wordValues: [
      { "player-yyLdQTaWb0xPj4v9AAAH-word-1": 8 },
      { "player-yyLdQTaWb0xPj4v9AAAH-word-2": 0 },
      { "player-yyLdQTaWb0xPj4v9AAAH-word-3": 0 },
      { "player-yyLdQTaWb0xPj4v9AAAH-word-4": 0 },
      { "player-yyLdQTaWb0xPj4v9AAAH-word-5": 0 },
      { "player-yyLdQTaWb0xPj4v9AAAH-word-6": 0 },
    ],
  },
];
