let x = {
  username: "c",
  socketId: "TmSU2VQzaIYJJpSfAAA7",
  room: "c",
  letters: [
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-0": "b" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-1": "d" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-2": "b" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-3": "c" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-4": "g" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-5": "u" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-6": "m" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-7": "z" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-8": "n" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-9": "c" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-10": "t" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-11": "e" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-12": "e" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-13": "p" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-14": "i" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-15": "j" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-16": "o" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-17": "c" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-18": "j" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-19": "n" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-20": "l" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-21": "x" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-22": "h" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-23": "a" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-24": "h" },
    { "player-TmSU2VQzaIYJJpSfAAA7-letter-25": "v" },
  ],
  words: [],
};
